#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
NS_ROOT=${NEURALSPOT_ROOT:-$SCRIPT_DIR}
cd "$NS_ROOT"

# Candidate VCAP read policy; see build_harvest_rf_replay_vcap_policy.sh.
# Identical to flash_harvest_rf_replay.sh except HVR4 and the last three flags.

make -B deploy \
  EXAMPLE=bisen_camera_harvest \
  PLATFORM=apollo4p_evb \
  AS_VERSION=R4.5.0 \
  BISEN_HARVEST_CALIBRATION_MODE=0 \
  BISEN_CAMERA_ENABLE_MRAM=1 \
  BISEN_HARVEST_CHECKPOINT_MAGIC=0x48565234 \
  BISEN_CAMERA_AUTORUN=0 \
  BISEN_HARVEST_AUTOCONTINUOUS=1 \
  BISEN_HARVEST_OFFLINE_VALIDATE=0 \
  BISEN_ENABLE_SWO_LOGGING=0 \
  BISEN_ENABLE_STATE_DAC=1 \
  BISEN_CAMERA_MAX_CHECKPOINTS=0 \
  BISEN_CAMERA_MAX_WAIT_CYCLES=0 \
  BISEN_HARVEST_SUPPLY_PIN=17 \
  BISEN_HARVEST_CAL_PIN=17 \
  BISEN_HARVEST_CAL_LOW_CODE=476 \
  BISEN_HARVEST_CAL_LOW_UV=5604455 \
  BISEN_HARVEST_CAL_HIGH_CODE=655 \
  BISEN_HARVEST_CAL_HIGH_UV=7705526 \
  BISEN_HARVEST_CRITICAL_UV=5800000 \
  BISEN_HARVEST_WORK100_UV=6200000 \
  BISEN_HARVEST_WORK500_UV=6800000 \
  BISEN_HARVEST_WORK1000_UV=7300000 \
  BISEN_HARVEST_STOP_CONFIRM=3 \
  BISEN_HARVEST_RESUME_CONFIRM=3 \
  BISEN_HARVEST_VCAP_SAMPLE_EVERY_STEPS=32
