local_app_name := bisen_port
local_src := $(wildcard $(subdirectory)/src/*.c)
local_src += $(wildcard $(subdirectory)/src/*.cc)
local_src += $(wildcard $(subdirectory)/src/*.cpp)
local_src += $(wildcard $(subdirectory)/src/*.s)
local_bin := $(BINDIR)/$(subdirectory)

# App-local linker extension reserves a non-loadable two-slot checkpoint area
# immediately after this app's loadable MRAM image. It does not change the
# generic neuralSPOT linker or any other application target.
LINKER_FILE := ./apps/bisen_port/bisen_checkpoint.ld

BISEN_ENABLE_DEBUG_LOGGING ?= 1
BISEN_ENABLE_VCAP_ADC ?= 0
BISEN_VCAP_ADC_PIN_CONFIRMED ?= 0
BISEN_ENABLE_ADC_DIAGNOSTIC ?= 0
BISEN_TEST_VCAP_MV ?= 0
BISEN_ENABLE_LOW_POWER ?= 0
BISEN_ENABLE_LOW_POWER_TEST ?= 0
BISEN_LOW_POWER_TEST_WAKE_LIMIT ?= 3
BISEN_ENABLE_INTEGRATED_CYCLE_TEST ?= 0
BISEN_INTEGRATED_CYCLE_TEST_WAKE_LIMIT ?= 50
BISEN_BOUNDED_NO_PROGRESS_WAKE_LIMIT ?= 3
BISEN_ENABLE_MRAM_CHECKPOINTS ?= 0
BISEN_ENABLE_COMPUTE_WORKLOAD ?= 0
BISEN_ENABLE_COMPUTE_RESUME_TEST ?= 0
BISEN_ENABLE_RESET_INJECTION ?= 0
BISEN_ENABLE_CHECKPOINT_ALTERNATION_TEST ?= 0
BISEN_RESET_INJECTION_PHASE ?= 0
BISEN_ENABLE_GPIO_INSTRUMENTATION ?= 0
BISEN_LOG_BACKEND ?= 1
BISEN_MRAM_SESSION_ATTEMPT_LIMIT ?= 64
BISEN_RESUME_VCAP_MV ?= 6100
BISEN_FORCE_DISABLE_MRAM_PROGRAMMING ?= 0
BISEN_ENABLE_RETENTION_TEST ?= 0
BISEN_RETENTION_TEST_WAKE_LIMIT ?= 3
BISEN_RETENTION_TRACE_WORKLOAD_REPEATS ?= 0
pp_defines += BISEN_ENABLE_DEBUG_LOGGING=$(BISEN_ENABLE_DEBUG_LOGGING)
pp_defines += BISEN_ENABLE_VCAP_ADC=$(BISEN_ENABLE_VCAP_ADC)
pp_defines += BISEN_VCAP_ADC_PIN_CONFIRMED=$(BISEN_VCAP_ADC_PIN_CONFIRMED)
pp_defines += BISEN_ENABLE_ADC_DIAGNOSTIC=$(BISEN_ENABLE_ADC_DIAGNOSTIC)
pp_defines += BISEN_TEST_VCAP_MV=$(BISEN_TEST_VCAP_MV)
pp_defines += BISEN_ENABLE_LOW_POWER=$(BISEN_ENABLE_LOW_POWER)
pp_defines += BISEN_ENABLE_LOW_POWER_TEST=$(BISEN_ENABLE_LOW_POWER_TEST)
pp_defines += BISEN_LOW_POWER_TEST_WAKE_LIMIT=$(BISEN_LOW_POWER_TEST_WAKE_LIMIT)
pp_defines += BISEN_ENABLE_INTEGRATED_CYCLE_TEST=$(BISEN_ENABLE_INTEGRATED_CYCLE_TEST)
pp_defines += BISEN_INTEGRATED_CYCLE_TEST_WAKE_LIMIT=$(BISEN_INTEGRATED_CYCLE_TEST_WAKE_LIMIT)
pp_defines += BISEN_BOUNDED_NO_PROGRESS_WAKE_LIMIT=$(BISEN_BOUNDED_NO_PROGRESS_WAKE_LIMIT)
pp_defines += BISEN_ENABLE_MRAM_CHECKPOINTS=$(BISEN_ENABLE_MRAM_CHECKPOINTS)
pp_defines += BISEN_ENABLE_COMPUTE_WORKLOAD=$(BISEN_ENABLE_COMPUTE_WORKLOAD)
pp_defines += BISEN_ENABLE_COMPUTE_RESUME_TEST=$(BISEN_ENABLE_COMPUTE_RESUME_TEST)
pp_defines += BISEN_ENABLE_RESET_INJECTION=$(BISEN_ENABLE_RESET_INJECTION)
pp_defines += BISEN_ENABLE_CHECKPOINT_ALTERNATION_TEST=$(BISEN_ENABLE_CHECKPOINT_ALTERNATION_TEST)
pp_defines += BISEN_RESET_INJECTION_PHASE=$(BISEN_RESET_INJECTION_PHASE)
pp_defines += BISEN_ENABLE_GPIO_INSTRUMENTATION=$(BISEN_ENABLE_GPIO_INSTRUMENTATION)
pp_defines += BISEN_LOG_BACKEND=$(BISEN_LOG_BACKEND)
pp_defines += BISEN_MRAM_SESSION_ATTEMPT_LIMIT=$(BISEN_MRAM_SESSION_ATTEMPT_LIMIT)
pp_defines += BISEN_RESUME_VCAP_MV=$(BISEN_RESUME_VCAP_MV)
pp_defines += BISEN_FORCE_DISABLE_MRAM_PROGRAMMING=$(BISEN_FORCE_DISABLE_MRAM_PROGRAMMING)
pp_defines += BISEN_ENABLE_RETENTION_TEST=$(BISEN_ENABLE_RETENTION_TEST)
pp_defines += BISEN_RETENTION_TEST_WAKE_LIMIT=$(BISEN_RETENTION_TEST_WAKE_LIMIT)
pp_defines += BISEN_RETENTION_TRACE_WORKLOAD_REPEATS=$(BISEN_RETENTION_TRACE_WORKLOAD_REPEATS)

bindirs   += $(local_bin)
examples  += $(local_bin)/$(local_app_name).axf
examples  += $(local_bin)/$(local_app_name).bin
mains     += $(local_bin)/src/$(local_app_name).o

$(eval $(call make-axf, $(local_bin)/$(local_app_name), $(local_src)))
