#!/usr/bin/env python3
"""
make_bench_vectors.py -- embed a fixed MNIST vector set and the host-reference
outputs of BOTH engines into src/bench_vectors.h, so the board checks its own
results (bit-exact) before any timing is trusted.

Inputs are stored once as 32x32 uint8 pixels (MNIST test image i, 2-pixel
zero border). The board derives each engine's own input encoding from them:
  RUIC     int8 = p - 128              (preprocess.c, NN_IN_SCALE 1/255, ZP -128)
  Capuchin Q5.10 = PIX_TO_Q10[p]       (Fxp(p/255, 16, 10), table generated here)
Expected scores come from host builds of the same sources (tools/host and the
RUIC engine compiled with the OS app's flags) and are cross-checked here
against the independent NumPy model (capuchin_ref.py).
"""
import argparse, hashlib, os, sys, subprocess
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import numpy as np
import ruic_model as rm, capuchin_ref as cr, mnist_idx, host_eval as he


def c_array(name, ctype, a, per_line=16):
    a = np.asarray(a).reshape(-1)
    body = ',\n'.join('  ' + ', '.join(str(int(v)) for v in a[i:i + per_line]) for i in range(0, len(a), per_line))
    return 'static const %s %s[%d] = {\n%s\n};\n' % (ctype, name, len(a), body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mnist-dir', required=True)
    ap.add_argument('--ruic-host', required=True, help='host build of the RUIC engine (stdin int8 -> scores)')
    ap.add_argument('--n', type=int, default=100)
    ap.add_argument('--first', type=int, default=0)
    ap.add_argument('--out', default=os.path.join(os.path.dirname(HERE), 'src', 'bench_vectors.h'))
    ap.add_argument('--msp430-n', type=int, default=16, help='vectors in the MSP430 cross-check header (FRAM-limited)')
    ap.add_argument('--msp430-out', default=os.path.join(os.path.dirname(HERE), 'msp430', 'capuchin_vectors.h'))
    a = ap.parse_args()
    X, Y = mnist_idx.load(a.mnist_dir, 'test')
    idx = np.arange(a.first, a.first + a.n)
    P = rm.mnist_pad32(X[idx]); lab = Y[idx]
    q10 = rm.capuchin_input_q10(P); i8 = rm.ruic_input_int8(P)
    table = rm.capuchin_input_q10(np.arange(256, dtype=np.uint8))
    assert np.array_equal(table[P], q10)

    hdr = os.path.join(os.path.dirname(HERE), 'src', 'capuchin', 'neural_network_parameters.h')
    arr = cr.model_array_from_header(hdr)
    exp = {}
    for k, binary in (('lea', 'host/host_capuchin_k1'), ('cpu', 'host/host_capuchin_k0')):
        s, l, _ = he.run_capuchin(os.path.join(HERE, binary), q10.reshape(a.n, -1))
        s2, l2 = cr.run(arr, q10[:, None], k)
        assert np.array_equal(s, s2) and np.array_equal(l, l2), 'host C and NumPy model disagree (%s)' % k
        exp[k] = (s, l)
    rs, rl = he.run_ruic(a.ruic_host, i8.reshape(a.n, -1))

    out = ['/* GENERATED by apps/bisen_capuchin/tools/make_bench_vectors.py -- do not edit. */',
           '#ifndef BENCH_VECTORS_H', '#define BENCH_VECTORS_H', '#include <stdint.h>',
           '#define BENCH_N %d' % a.n,
           '#define BENCH_MNIST_TEST_FIRST %d  /* MNIST t10k index of vector 0 */' % a.first,
           '#define BENCH_MODEL_ARRAY_SHA256 "%s"' % hashlib.sha256(arr.astype('<i2').tobytes()).hexdigest(),
           '/* host-reference accuracy on these vectors: capuchin(lea) %d/%d, capuchin(cpu) %d/%d, ruic %d/%d */'
           % ((exp['lea'][1] == lab).sum(), a.n, (exp['cpu'][1] == lab).sum(), a.n, (rl == lab).sum(), a.n),
           c_array('BENCH_PIX', 'uint8_t', P),
           c_array('BENCH_LABEL', 'uint8_t', lab),
           c_array('PIX_TO_Q10', 'int16_t', table),
           '/* Capuchin expected Q5.10 logits: LEA-path kernels (CAPUCHIN_KERNEL 1 and 2) */',
           c_array('BENCH_CAP_LEA_SCORES', 'int16_t', exp['lea'][0]),
           c_array('BENCH_CAP_LEA_LABEL', 'uint8_t', exp['lea'][1]),
           '/* Capuchin expected Q5.10 logits: upstream CPU path (CAPUCHIN_KERNEL 0) */',
           c_array('BENCH_CAP_CPU_SCORES', 'int16_t', exp['cpu'][0]),
           c_array('BENCH_CAP_CPU_LABEL', 'uint8_t', exp['cpu'][1]),
           '/* RUIC engine (engine-r2a, OS) expected int8 scores */',
           c_array('BENCH_RUIC_SCORES', 'int8_t', rs),
           c_array('BENCH_RUIC_LABEL', 'uint8_t', rl),
           '#endif']
    open(a.out, 'w').write('\n'.join(out) + '\n')

    # MSP430 cross-check set: the first msp430_n of the same vectors and the SAME
    # expected Capuchin outputs (LEA path). Native == Apollo4 port on these
    # vectors is gate X1 (bit-exact cross-platform equivalence).
    m = a.msp430_n
    msp = ['/* GENERATED by apps/bisen_capuchin/tools/make_bench_vectors.py -- do not edit.',
           ' * Cross-check vectors for native Capuchin on MSP430FR5994 (gate X1). Identical',
           ' * to vectors 0..%d of the Apollo4 bench (MNIST t10k[%d..%d], 2-pixel border).' % (m - 1, a.first, a.first + m - 1),
           ' * Expected values: Capuchin LEA path, computed on the host from the same',
           ' * MODEL_ARRAY (sha256 %s). */' % hashlib.sha256(arr.astype('<i2').tobytes()).hexdigest(),
           '#ifndef CAPUCHIN_VECTORS_H', '#define CAPUCHIN_VECTORS_H', '#include <stdint.h>',
           '#define XCHK_N %d' % m,
           c_array('XCHK_PIX', 'uint8_t', P[:m]),
           c_array('XCHK_LABEL', 'uint8_t', lab[:m]),
           c_array('XCHK_PIX_TO_Q10', 'int16_t', table),
           c_array('XCHK_EXPECTED_SCORES', 'int16_t', exp['lea'][0][:m]),
           c_array('XCHK_EXPECTED_LABEL', 'uint8_t', exp['lea'][1][:m]),
           '#endif']
    open(a.msp430_out, 'w').write('\n'.join(msp) + '\n')
    print('wrote', a.out, 'acc lea/cpu/ruic =', (exp['lea'][1] == lab).mean(), (exp['cpu'][1] == lab).mean(), (rl == lab).mean())


if __name__ == '__main__':
    main()
